name: sample-springboot
services:
- dockerfile_path: /Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: ErikBustos/sample-spring-boot-digitalOcean
  name: sample-springboot
  envs:
    - key: DB_URL
      scope: RUN_TIME
      value: ${db.HOSTNAME}
    - key: DB_USER
      scope: RUN_TIME
      value: ${db.USERNAME}
    - key: DB_PASSWORD
      scope: RUN_TIME
      value: ${db.PASSWORD}