name: sample-springboot
services:
- dockerfile_path: /Dockerfile
  github:
    branch: development
    deploy_on_push: true
    repo: ErikBustos/sample-spring-boot-digitalOcean
  name: sample-springboot